import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import { useState } from "react";

const Home: NextPage = () => {
  const msgs = trpc.example.allMsgs.useQuery();
  const addi = trpc.example.addMsg.useMutation({
    onSuccess: () => {
      msgs.refetch();
    },
  });

  const [formData, setFormData] = useState("oi");

  function handleSubmit() {
    addi.mutate({ msg: formData });
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b ">
        <input
          className="border "
          type="text"
          value={formData}
          onChange={(e) => setFormData(e.target.value)}
        />
        <button className="border-4 border-black" onClick={handleSubmit}>
          mandar
        </button>

        {msgs &&
          msgs.data?.map((mensagem) => {
            return <p>{mensagem.msg}</p>;
          })}
      </main>
    </>
  );
};

export default Home;
